/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIChatContainer: typeof import('./src/components/AIChatContainer.vue')['default']
    Bubble: typeof import('./src/components/Bubble.vue')['default']
    BubbleList: typeof import('./src/components/BubbleList.vue')['default']
    ChatButton: typeof import('./src/components/ChatButton.vue')['default']
    ChatIcon: typeof import('./src/components/ChatIcon.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatInputAdapter: typeof import('./src/components/ChatInputAdapter.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ChatView: typeof import('./src/components/ChatView.vue')['default']
    Conversations: typeof import('./src/components/Conversations.vue')['default']
    DialogEdit: typeof import('./src/components/DialogEdit.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    PopupMenu: typeof import('./src/components/PopupMenu.vue')['default']
    RestoreDialog: typeof import('./src/components/RestoreDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./src/components/SearchDialog.vue')['default']
    Sender: typeof import('./src/components/Sender.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    StreamMonitor: typeof import('./src/components/StreamMonitor.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    TooltipButton: typeof import('./src/components/TooltipButton.vue')['default']
  }
}
